spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/surveydb
    username: root
    password: root123$
  data:
    mongodb:
      database: surveydata
      port: '27017'
      host: localhost
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'

#JWT
jwt:
  get:
    token:
      uri: /authenticate
  secret: survey
